version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cada003-hello-from-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-pmwwgbzgw6qt"
s3_prefix = "cada003-hello-from-lambda"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
